plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

ext {
    plVersion = '6.3.2'
}

allprojects {
    group = 'me.dablakbandit'
    version = plVersion

    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
            content {
                includeGroup 'org.bukkit'
                includeGroup 'org.spigotmc'
            }
        }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url = 'https://ci.lucko.me/plugin/repository/everything/' }
        maven { url = 'https://nexus.velocitypowered.com/repository/maven-public/' }
        maven { url = 'https://jitpack.io' }
        maven { url "https://repo.spongepowered.org/repository/maven-public" }
        maven { url = 'https://libraries.minecraft.net/' }
    }
}

subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    compileJava {
        options.encoding = 'UTF-8'
    }

    ext {
        bukkitVersion = '1.20.2-R0.1-SNAPSHOT'
        aoVersion = plVersion
    }
}